# Generated by Django 5.1.7 on 2025-03-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
